### ISSUE TITLE
id's for style

### ISSUE THREAD

**Issue by FutureKode** [kickserv/dojo#3]
How do you feel about using id’s for style? I feel that we should use classes as much as possible to avoid inheritance issues. And if you agree we should enforce that rule in the docs

![screen shot on 2015-06-04 at 11-33-31](https://cloud.githubusercontent.com/assets/332387/7983186/73b09cfc-0ab5-11e5-9c31-e47c4438761c.png)

**Comment by briannelson** [comment]
I agree with this for production, for sure. I'm ok with it for these specific examples, though, as there's no really good way to do it otherwise.
